<!--
 API Documentation HTML Template  - 1.0.1
 Copyright © 2016 Florian Nicolas
 Licensed under the MIT license.
 https://github.com/ticlekiwi/API-Documentation-HTML-Template
 !-->
<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <title>API - Documentation</title>
    <meta name="description" content="">
    <meta name="author" content="ticlekiwi">

    <meta http-equiv="cleartype" content="on">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ asset('assets/img/favicon.ico') }}" type="image/x-icon"/>
    <link rel="stylesheet" href="{{ asset('assets/documentation/css/hightlightjs-dark.css') }}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/highlight.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,500|Source+Code+Pro:300" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('assets/documentation/css/style.css') }}" media="all">
    <script>
        hljs.initHighlightingOnLoad();
    </script>
    <style>
        pre {
            float: left !important;
        }
    </style>
</head>

<body class="one-content-column-version">
<div class="left-menu">
    <div class="content-logo" style="display: block;">
        <img alt="platform by Emily van den Heever from the Noun Project" title="platform by Emily van den Heever from the Noun Project" src="{{ asset('assets/documentation/images/logo.png') }}" height="32" />
        <span>Qraved CMS</span><br><br>
        <span>API Documentation</span>
    </div>
    <div class="content-menu">
        <ul>
            <li class="scroll-to-link active" data-target="get-started">
                <a>GET STARTED</a>
            </li>
            <li class="scroll-to-link" data-target="qr-code-resto">
                <a>QR Code resto</a>
            </li>
            <li class="scroll-to-link" data-target="get-user-data">
                <a>Get user data</a>
            </li>
            <li class="scroll-to-link" data-target="store-user-data">
                <a>Store user data</a>
            </li>
            <li class="scroll-to-link" data-target="get-random-quiz">
                <a>Get random quiz</a>
            </li>
            <li class="scroll-to-link" data-target="answer-the-question">
                <a>Answer the question</a>
            </li>
            <li class="scroll-to-link" data-target="store-custom-user-log">
                <a>Store custom user log</a>
            </li>
            <li class="scroll-to-link" data-target="get-data-resto">
                <a>Get data resto</a>
            </li>
        </ul>
    </div>
</div>


<div class="content-page">
    <div class="content">
        <div class="overflow-hidden content-section" id="content-get-started">
            <h1 id="get-started">Get started</h1>
            <p>
                Qraved CMS API
            </p>
            <p>
                API end point: <br>
                <code>{{ url('/api') }}</code>
            </p>
        </div>
        <div class="overflow-hidden content-section" id="content-qr-code-resto">
            <h2 id="qr-code-resto">QR Code Resto</h2>
            <p>
                Structure of QR Code link :<br>
                <code class="higlighted">{url}?{key_param}={value_param}</code>
            </p>
            <br>
            <h4>Explain</h4>
            <table>
                <tr>
                    <td>url</td>
                    <td>Can be set in the "Setting" menu</td>
                </tr>
                <tr>
                    <td>key_param</td>
                    <td>Can be set in the "Setting" menu</td>
                </tr>
                <tr>
                    <td>value_param</td>
                    <td>Generated by "QR Code" menu</td>
                </tr>
            </table>
        </div>
        <div class="overflow-hidden content-section" id="content-get-user-data">
            <h2 id="get-user-data">Get user data</h2>
            <p>
                Get data qraved users who have registered in the cms database: <br>
                <code>{{ url('/api/user/get') }}/{qraved_user_id}</code>
            </p>
            <h4>Explain</h4>
            <table>
                <tr>
                    <td>method</td>
                    <td>GET</td>
                </tr>
                <tr>
                    <td>{qraved_user_id}</td>
                    <td>User ID of the Qraved</td>
                </tr>
            </table>
            <h4>Query Parameters</h4>
            <table>
                <tr>
                    <td>NONE</td>
                </tr>
            </table>
            <h4>Return</h4>
            <pre>
{
    "success": true,
    "message": "",
    "data": {
        "user": {
            "qraved_user_mapping_id": "{string}",
            "email": "{string}",
            "contact": "{string}",
            "gender": "{char}",
            "birth_date": "{yyyy-mm-dd}",
            "interest": "{string}",
            "job": "{string}"
        }
    }
}
            </pre>
        </div>
        <div class="overflow-hidden content-section" id="content-store-user-data">
            <h2 id="store-user-data">Store user data</h2>
            <p>
                Register the qraved user to CMS database: <br>
                <code>{{ url('/api/user/store') }}</code>
            </p>
            <h4>Explain</h4>
            <table>
                <tr>
                    <td>method</td>
                    <td>POST</td>
                </tr>
            </table>
            <h4>Request</h4>
            <table>
                <tr>
                    <td>qraved_id</td>
                    <td>required</td>
                </tr>
                <tr>
                    <td>email</td>
                    <td>required, valid email format</td>
                </tr>
                <tr>
                    <td>contact</td>
                    <td>required</td>
                </tr>
                <tr>
                    <td>gender</td>
                    <td>required, 1 character</td>
                </tr>
                <tr>
                    <td>birth_date</td>
                    <td>required | valid date format (yyyy-mm-dd)</td>
                </tr>
                <tr>
                    <td>interest</td>
                    <td>required</td>
                </tr>
                <tr>
                    <td>job</td>
                    <td>required</td>
                </tr>
            </table>
            <h4>Return</h4>
            <pre>
{
    "success": true,
    "message": "",
    "data": {
        "user": {
            "qraved_user_mapping_id": "{string}",
            "email": "{string}",
            "contact": "{string}",
            "gender": "{char}",
            "birth_date": "{yyyy-mm-dd}",
            "interest": "{string}",
            "job": "{string}"
        }
    }
}
            </pre>
        </div>
        <div class="overflow-hidden content-section" id="content-get-random-quiz">
            <h2 id="get-random-quiz">Get random quiz</h2>
            <p>
                Getting random quiz: <br>
                <code>{{ url('/api/quiz/get') }}</code>
            </p>
            <h4>Explain</h4>
            <table>
                <tr>
                    <td>method</td>
                    <td>GET</td>
                </tr>
            </table>
            <h4>Query Parameters</h4>
            <table>
                <tr>
                    <td>user</td>
                    <td>required (qraved_id)</td>
                </tr>
                <tr>
                    <td>resto</td>
                    <td>required (resto_id)</td>
                </tr>
            </table>
            <h4>Return</h4>
            <pre>
{
    "success": true,
    "message": "",
    "data": {
        "id": {integer},
        "question": "{string}",
        "question_images": {array (string)},
        "answer_type": {integer},
        "answer": {array (json {
            "text" : {string},
            "correct" : {boolean}
        })}
    }
}
            </pre>
        </div>
        <div class="overflow-hidden content-section" id="content-answer-the-question">
            <h2 id="answer-the-question">Answer the question</h2>
            <p>
                Answer the question: <br>
                <code>{{ url('/api/quiz/answer-question') }}</code>
            </p>
            <h4>Explain</h4>
            <table>
                <tr>
                    <td>method</td>
                    <td>POST</td>
                </tr>
            </table>
            <h4>Request</h4>
            <table>
                <tr>
                    <td>user</td>
                    <td>required (qraved_id)</td>
                </tr>
                <tr>
                    <td>resto</td>
                    <td>required (resto_id)</td>
                </tr>
                <tr>
                    <td>question_id</td>
                    <td>required, integer</td>
                </tr>
                <tr>
                    <td>status</td>
                    <td>boolean</td>
                </tr>
            </table>
            <h4>Return</h4>
            <pre>
{
    "success": true,
    "message": "",
    "data": []
}
            </pre>
        </div>
        <div class="overflow-hidden content-section" id="content-store-custom-user-log">
            <h2 id="store-custom-user-log">Store custom user log</h2>
            <p>
                Store custom user log: <br>
                <code>{{ url('/api/user-log/store') }}</code>
            </p>
            <h4>Explain</h4>
            <table>
                <tr>
                    <td>method</td>
                    <td>POST</td>
                </tr>
            </table>
            <h4>Request</h4>
            <table>
                <tr>
                    <td>user</td>
                    <td>required (qraved_id)</td>
                </tr>
                <tr>
                    <td>resto</td>
                    <td>required (resto_id)</td>
                </tr>
                <tr>
                    <td>action</td>
                    <td>required, string</td>
                </tr>
            </table>
            <h4>Return</h4>
            <pre>
{
    "success": true,
    "message": "",
    "data": []
}
            </pre>
        </div>
        <div class="overflow-hidden content-section" id="content-get-data-resto">
            <h2 id="get-data-resto">Get data resto</h2>
            <p>
                Get registered restaurant data: <br>
                <code>{{ url('/api/resto/get/{unique_code}') }}</code>
            </p>
            <h4>Explain</h4>
            <table>
                <tr>
                    <td>method</td>
                    <td>get</td>
                </tr>
                <tr>
                    <td>{unique_code}</td>
                    <td>Unique code on qr code link</td>
                </tr>
            </table>
            <h4>Return</h4>
            <pre>
{
    "success": true,
    "message": "",
    "data": {
        "restaurant": {
            "id": {integer},
            "qraved_resto_mapping_id": {integer},
            "name": {string},
            "alias": {string},
            "address": {string},
            "contact": {string},
            "qr_id": {integer}
        }
    }
}
            </pre>
        </div>
    </div>
</div>
<script src="{{ asset('assets/documentation/js/script.js') }}"></script>
</body>

</html>
